#   ============================================================
#   continuous integration setup 
#   ============================================================
#   created by Manfred Sorgo
name: C/C++ CI

on:
    push:
        branches: [ 'dev' ]
    pull_request:
        branches: [ 'dev' ]

jobs:
    buildConfigs:

        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        -   name: build config "silent"
            run: cd make; git clean -dxf .; make -j -f TCP_Srv_Echo.make config=silent
        -   name: build config "verbose"
            run: cd make; git clean -dxf .; make -j -f TCP_Srv_Echo.make config=verbose
