#   ============================================================
#   continuous integration setup 
#   ============================================================
#   created by Manfred Sorgo
name: C/C++ CI

on:
    push:
        branches: [ 'dev' ]
    pull_request:
        branches: [ 'dev' ]

jobs:
    buildConfigs:

        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        -   name: prepare build
            run: chmod 755 make/build.sh
        -   name: build config "prod"
            run: make/build.sh -p
        -   name: build config "verbose"
            run: make/build.sh -v
        -   name: build config "vsmall"
            run: make/build.sh -s
